# serverless.yml
plugins: # List of plugins of use on application
  - serverless-offline # Get your serverless configuration and run the server local
  - serverless-dotenv-plugin # Help with .env management files
service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true